export enum ListingVisibility {
  STANDARD = 'STANDARD',
  FEATURED = 'FEATURED',
}

export enum FeaturedPlan {
  FEATURED_7 = 'FEATURED_7',
  FEATURED_14 = 'FEATURED_14',
  FEATURED_30 = 'FEATURED_30',
  FEATURED_60 = 'FEATURED_60',
  FEATURED_90 = 'FEATURED_90',
  FEATURED_120 = 'FEATURED_120',
  FEATURED_180 = 'FEATURED_180',
}

export enum ListingStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  SUSPENDED = 'SUSPENDED',
  ARCHIVED = 'ARCHIVED',
}

export enum ListingPurpose {
  ALL = 'ALL',
  RENT = 'RENT',
  SELL = 'SALE'
}